server:
  port: ${APPLICATION_PORT}

spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:3306/${DATABASE_NAME}?characterEncoding=UTF8&useSSL=false
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    generate-ddl: false
  flyway:
    enabled: true
  config:
    import: optional:file:.env.example[.yml]
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

weixin:
  mp:
    app-id: ${MP_APP_ID}
    app-secret: ${MP_APP_SECRET}

cos:
  bucket: ${COS_BUCKET}
  secret-id: ${COS_SECRET_ID}
  secret-key: ${COS_SECRET_KEY}
  region: ${COS_REGION}


